### ISSUE TITLE
Not able to create a shopping feed account at MARKETING->Shopping Feed->Accounts

### ISSUE THREAD

**Issue by arslan-eg** [shoppingflux/module-magento2#100]
In magento2 Admin Panel
When I navigate MARKETING->Shopping Feed->Accounts
and add use name password 
then click on Create Account Button

It shows exception.
Could not create the account on Shopping Feed. Please try again later.

![image](https://user-images.githubusercontent.com/75121002/116654800-51ad3000-a9a3-11eb-8d7a-585281034acf.png)

After debug I notice that
this API is not working anymore 

https://connectors.shopping-feed.com/api/magento/register

is there any other API for this module or I'm missing something. 

Thank you!

**Comment by blmage** [comment]
After checking with the API team, it turns out that registration is not available for South Korea.

A better error message will be added in the next version for this specific case.

Please contact us at contact@shopping-feed.com if you have any question!
