### ISSUE TITLE
Issue with magento 2.4.4

### ISSUE THREAD

**Issue by sebfie** [shoppingflux/module-magento2#111]
Hello,

When Trying to update to magento 2.4.4 I have this issue : 

 Problem 1
    - magento/product-community-edition 2.4.4 requires magento/framework 103.0.4 -> satisfiable by magento/framework[103.0.4].
    - Conclusion: don't install guzzlehttp/guzzle 7.4.2
    - Conclusion: don't install guzzlehttp/guzzle 7.4.1
    - Installation request for magento/product-community-edition 2.4.4 -> satisfiable by magento/product-community-edition[2.4.4].
    - Installation request for shoppingfeed/magento2-manager ^0.53 -> satisfiable by shoppingfeed/magento2-manager[0.53.0, 0.53.1, 0.53.2].
    - magento/framework 103.0.4 requires guzzlehttp/guzzle ^7.3.0 -> satisfiable by guzzlehttp/guzzle[7.3.0, 7.4.0, 7.4.1, 7.4.2].
    - Can only install one of: guzzlehttp/guzzle[7.3.0, 6.5.4].
    - Can only install one of: guzzlehttp/guzzle[7.4.0, 6.5.4].
    - Conclusion: install guzzlehttp/guzzle 6.5.4

Can you maybe just change dependencies to guzzlehttp/guzzle > 6.5 ? 

Thank you

**Comment by blmage** [comment]
Thanks for the report!

Dependency ranges have been bumped in version `0.54.0`.
