### ISSUE TITLE
Incompatibility with PHP 8

### ISSUE THREAD

**Issue by benjamin-volle** [shoppingflux/module-magento2#118]
There is an issue when using the module with PHP 8.1 :

In the file view/adminhtml/ui_component/sfm_account_store_form.xml , the block "ShoppingFeed\Manager\Block\Adminhtml\Feed\Product\Grid\Wrapper" is declared as an argument, without name.

But, in the class \Magento\PricePermissions\Observer\AdminhtmlBlockHtmlBeforeObserver::execute, using "stripos" on null is deprecated since PHP 8.

So, the patch would be replacing : 
`<argument name="block" xsi:type="object">ShoppingFeed\Manager\Block\Adminhtml\Feed\Product\Grid\Wrapper</argument>
`
by
`                <block name="sfm.feed_product.grid.wrapper" class="ShoppingFeed\Manager\Block\Adminhtml\Feed\Product\Grid\Wrapper"/>`

in the file view/adminhtml/ui_component/sfm_account_store_form.xml on line 53

Steps to reproduce :
- install a fresh Magento 2.4.x using PHP 8.1
- go to admin panel in marketing > shopping feed > accounts
- select an account

**Comment by blmage** [comment]
Thanks for reporting this issue, and for the correct fix!

Fixed by a5bcfcca7cdd28842f5662182007bf04a2431853 / in version [1.2.1](https://github.com/shoppingflux/module-magento2/releases/tag/1.2.1).
