### ISSUE TITLE
Error during compilation on 1.5.0 with php8.1

### ISSUE THREAD

**Issue by nverhoye** [shoppingflux/module-magento2#127]
Bonjour,

Il y a une erreur lors de la compilation de la toute dernière version du module 1.5.0

err Error during compilation
err setup:di:compile
Compilation was started.
Errors during compilation:
ShoppingFeed\Manager\Block\Adminhtml\Feed\ForceRefreshButton
Incompatible argument type: Required type: int. Actual type: string; File:
/var/www/html/magento2/releases/904/vendor/shoppingfeed/magento2-manager/Block/Adminhtml/Feed/ForceRefreshButton.php

J'utilise php 8.1

**Comment by blmage** [comment]
Bonjour Nicolas,

Merci pour le retour ! Le problème devrait être corrigé avec la version **1.5.1**.
