### ISSUE TITLE
Mode de paiement = Shopping Feed Order ?

### ISSUE THREAD

**Issue by IndeedEvan** [shoppingflux/module-magento2#132]
Bonjour,

Après avoir configuré le  **Titre du mode de paiement par défaut** et  **Titre du mode de paiement par place de marché**, j'ai effectivement le bon nom de moyen de paiement et/ou marketplace sur la facture. En revanche sur l'affichage des factures, dans la colonne "Mode de paiement" j'ai toujours "Shopping Feed Order" qui s'affiche. 

Cette colonne est utile pour la logistique et la comptabilité, est-il possible d'afficher le nom paramétré dans le titre du mode de paiement par défaut ?

![Capture d'écran 2023-09-19 134624](https://github.com/shoppingflux/module-magento2/assets/12630507/eb29dc62-5f50-4b6b-a923-203fb99c248b)

Merci à vous ! :)

**Comment by blmage** [comment]
Effectivement, la colonne "Mode de paiement" se base sur le champ `sales_order_payment`.`method` pour déterminer le titre à afficher en fonction de la configuration actuelle, alors que les titres spécifiques aux PDM se trouvent dans le champ `sales_order_payment`.`additional_information` (encodé en JSON).

Malheureusement, adapter la colonne existante ou en ajouter une nouvelle pour corriger ce problème sortirait du périmètre de l'extension, mais n'hésitez pas à contacter le [support Shoppingfeed](https://support.shoppingfeed.com/hc/fr/requests/new) si besoin d'aide à ce niveau.
