### ISSUE TITLE
Issue with Token login process

### ISSUE THREAD

**Issue by achatpc** [shoppingflux/module-magento2#14]
Hello,

When i try to connect my Magento 2 website to Shopping feed, i have this error after token write step:

Fatal error: Uncaught Error: Class 'ShoppingFeed\Sdk\Credential\Token' not found in /var/www/html/app/code/ShoppingFeed/Manager/Model/ShoppingFeed/Api/SessionManager.php:62 Stack trace: #0 /var/www/html/app/code/ShoppingFeed/Manager/Model/Account/Importer.php(135): ShoppingFeed\Manager\Model\ShoppingFeed\Api\SessionManager->getSessionByToken('7e95e332a44cece...') #1 /var/www/html/app/code/ShoppingFeed/Manager/Model/Account/Importer.php(166): ShoppingFeed\Manager\Model\Account\Importer->getApiSessionByToken('7e95e332a44cece...') #2 /var/www/html/app/code/ShoppingFeed/Manager/Controller/Adminhtml/Account/Create/Existing.php(62): ShoppingFeed\Manager\Model\Account\Importer->importAccountByApiToken('7e95e332a44cece...', false, 1) #3 /var/www/html/vendor/magento/framework/App/Action/Action.php(107): ShoppingFeed\Manager\Controller\Adminhtml\Account\Create\Existing->execute() #4 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Req in /var/www/html/app/code/ShoppingFeed/Manager/Model/ShoppingFeed/Api/SessionManager.php on line 62

Thank you in advance for your help

php-sdk is installed in /vendor/shoppingfeed/php-sdk/
php-feed-generator is installed in /vendor/shoppingfeed/php-feed-generator
shoppingflux/module-magento2 is installed in /app/code/ShoppingFeed/Manager/
I have not use composer for install package but i have just copy/past source folders and set correct access write. php bin/setup:upgrade command successful.

**Comment by achatpc** [comment]
Fixed with php-sdk 0.2.4.

Thank you!

**Comment by clement-hollander** [comment]
Thanks @achatpc for your feedback ;)
