### ISSUE TITLE
Shipping Method Rules KO on BO

### ISSUE THREAD

**Issue by khaitchrif** [shoppingflux/module-magento2#38]
When I am trying to get 'Shipping Method Rules' (on BO),I am getting this error.

**1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Element 'settings': This element is not expected. Expected is one of ( paging, listingToolbar, filters, massaction, dataSource, columns, container ).
Line: 8**

origin issue:
shoppingfeed use "urn:magento:module:Magento_Ui:etc/ui_configuration.xsd" as noNamespaceSchemaLocation  and vendor/magento/module-ui/etc/ui_configuration.xsd don't have 'settings' element

Could you check that on your side !

FYI:
I am installing this module on Magento version 2.1.11.

Thanks

**Comment by blmage** [comment]
We are aware of some compatibility problems with M 2.1.X, which is the next thing we'll be looking into, right after having released a new version taking M 2.3 features into account.
In the meantime, if you happen to find some other related problems, don't hesitate to post them here!

**Comment by khaitchrif** [comment]
would it be possible to have a date on the correction of this problem?

Thanks

**Comment by khaitchrif** [comment]
Hello, 
would it be possible to have a date on the correction of this problem?

**Comment by blmage** [comment]
Sorry for the delay! Unforeseen circumstances took the priority over this issue.

We are now actively working on this, and will provide an ETA asap (as soon as we have a full view on all the things that should be fixed).

In any case, here is what has been done so far (the list will be updated as we go):
- [x] Remove usage of `\Magento\Framework\Serialize\Serializer\Json`
- [x] Fix constructor of `\ShoppingFeed\Manager\Model\Shipping\Method\Rule`
- [x] Fix uses of `Magento\Framework\Message\ManagerInterface::addExceptionMessage()`
- [ ] Rewrite the configuration of UI components (use the old schema definition) - _in progress_

**Comment by blmage** [comment]
The new version (0.19.0) that fixes compatibility problems with Magento 2.1.x is now [available](https://github.com/shoppingflux/module-magento2/releases/tag/0.19.0).
