### ISSUE TITLE
orders are not importing

### ISSUE THREAD

**Issue by aphoboth** [shoppingflux/module-magento2#7]
module was successfully installed via composer and API token configured.
Expected behavior :
orders should be automatically imported from shopping-flux dashboard into magento

Current Behavior :
orders are not imported. No manual orders import button found or command.

Thanks

**Comment by benoit-apk** [comment]
Thanks for your report, this feature has not been fully implemented yet, but it should be available at the latest in the course of next week!

**Comment by aphoboth** [comment]
Hello, now installed new version. Which command can be executed in order to import the orders to magento? Thanks

**Comment by blmage** [comment]
Sorry for the delay!
The latest versions of the module now ship with pre-installed cron tasks, so apart from specific needs you should not need CLI commands anymore.
