### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by rafalinco** [shoppingflux/module-magento2#9]
Hi,

When I try to Install Shopping feed this extension in our magento 2.2.3, must need 2 library and if i install that library through composer then it throws the error which I attached in message.

![error](https://user-images.githubusercontent.com/41475442/43000827-450e4866-8c23-11e8-9460-edcbee0b3694.png)

**Comment by benoit-apk** [comment]
Can you try installing the `shoppingfeed/php-sdk` package with an explicit version?

For example, currently:
`composer require shoppingfeed/php-sdk@0.2.1-beta.1`

**Comment by blmage** [comment]
Sorry for the delay!
The module should be much simpler to install now as itself and every dependence is marked as "stable".
In any case, if needed, you can find installation instructions here : https://github.com/shoppingflux/module-magento2/wiki/Installation.
